name: Build CloudNode APK

on:
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate translations only
        run: dart run slang

      - name: Build Debug APK
        run: flutter build apk --debug --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CloudNode-Android-Debug-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
